- name: Configuring Basic Topology
  hosts: all
  gather_facts: False
  tags: basic
  tasks: 

    - name: Turn on interfaces
      ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
            enabled: true
        state: merged
      loop: "{{ interfaces }}"
      tags: enableintf

    - name: Configure interface addresses
      ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ipv4 }}"
            ipv6:
              - address: "{{ item.ipv6 }}"
                link_local: yes
        state: merged
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "item.mode is L3"
      tags: addresses

    - name: Configure IPv6 link-local addresses
      cisco.ios.ios_config:
        lines:
          - ipv6 address {{ item.link_local | ansible.netcommon.ipaddr('address') }} link-local
        parents: interface {{ item.name }}
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.link_local is defined
      tags: linklocal

    - name: Gather listed l3 interfaces with provided configurations
      cisco.ios.ios_l3_interfaces:
        state: gathered
      tags: gat


    - name:  Parsed listed l3 interfaces with provided configurations
      cisco.ios.ios_l3_interfaces:
        running_config: 
        state: parsed
      tags: parse