---
# tasks file for motd_banner
- ios_banner:
    banner: motd
    text: |
      Attention - This is a secure network device
      Authorized personal only should connect and manage
      this device.

      Disconnect immediately if not approved.
    state: present